apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: newnginx
    type: canary
  name: newnginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newnginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: newnginx
        type: canary
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
        - name: configfile
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: configfile
        configMap:
          name: newnginx
status: {}
